/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formulario2;
import Codigo.Conexion; 
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
/**
 *
 * @author User
 */
public class RedactarC extends javax.swing.JInternalFrame {

    /**
     * Creates new form RedactarC
     */
    public RedactarC() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        IDproductos = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ResenaField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        SiDieta3 = new javax.swing.JRadioButton();
        Nodieta3 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        MalaCal1 = new javax.swing.JRadioButton();
        BuenaCal1 = new javax.swing.JRadioButton();
        conectar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nuevo Cliente");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        IDproductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Producto", "Item 2", "Item 3", "Item 4" }));
        IDproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDproductosActionPerformed(evt);
            }
        });

        jLabel13.setText("Producto:");

        jLabel14.setText("Reseña:");

        ResenaField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResenaField3ActionPerformed(evt);
            }
        });

        jLabel15.setText("Es Dietetico?.");

        SiDieta3.setText("Si");
        SiDieta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiDieta3ActionPerformed(evt);
            }
        });

        Nodieta3.setText("No");
        Nodieta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nodieta3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Calificacion:");

        MalaCal1.setText("Mala");
        MalaCal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalaCal1ActionPerformed(evt);
            }
        });

        BuenaCal1.setText("Buena");
        BuenaCal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuenaCal1ActionPerformed(evt);
            }
        });

        conectar.setText("Enviar");
        conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Redactar Critica");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResenaField3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(56, 56, 56)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(Nodieta3)
                    .addComponent(SiDieta3)
                    .addComponent(jLabel16)
                    .addComponent(MalaCal1)
                    .addComponent(BuenaCal1)
                    .addComponent(conectar))
                .addGap(53, 53, 53))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SiDieta3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nodieta3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MalaCal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuenaCal1))
                            .addComponent(ResenaField3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addComponent(conectar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDproductosActionPerformed

    private void ResenaField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResenaField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResenaField3ActionPerformed

    private void SiDieta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiDieta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiDieta3ActionPerformed

    private void Nodieta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nodieta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nodieta3ActionPerformed

    private void MalaCal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalaCal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MalaCal1ActionPerformed

    private void BuenaCal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuenaCal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuenaCal1ActionPerformed

    private void conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarActionPerformed
                                      
// Obtener valores de los campos
    String producto = (String) IDproductos.getSelectedItem();
    String resena = ResenaField3.getText().trim(); // Elimina espacios adicionales
    boolean dietetico = SiDieta3.isSelected();
    String calificacion = MalaCal1.isSelected() ? "Mala" : "Buena";

    // Validar que la reseña no esté vacía
    if (resena.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "La reseña no puede estar vacía.");
        return;
    }

    // Intentar insertar en la base de datos
    try (Connection con = Conexion.getInstance().getConnection()) {
        String query = "INSERT INTO Pastel (producto, resena, dietetico, calificacion) VALUES (?, ?, ?, ?)";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, producto);
        ps.setString(2, resena);
        ps.setBoolean(3, dietetico);
        ps.setString(4, calificacion);
        ps.executeUpdate();
    if (resena.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "La reseña no puede estar vacía.");
    return;
    }
        // Mensaje de confirmación
        javax.swing.JOptionPane.showMessageDialog(this, "Crítica guardada exitosamente.");
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la crítica: " + e.getMessage());
    }

    }//GEN-LAST:event_conectarActionPerformed
private void cargarProductos() {
    // Intentar cargar los nombres de productos desde la base de datos
    try (Connection con = Conexion.getInstance().getConnection()) {
        String query = "SELECT nombre FROM Pastel"; // Ajusta "nombre" si tu columna tiene otro nombre
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        IDproductos.removeAllItems(); // Limpia el ComboBox antes de cargar los productos
        while (rs.next()) {
            IDproductos.addItem(rs.getString("nombre")); // Agregar cada producto al ComboBox
        }
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BuenaCal1;
    private javax.swing.JComboBox<String> IDproductos;
    private javax.swing.JRadioButton MalaCal1;
    private javax.swing.JRadioButton Nodieta3;
    private javax.swing.JTextField ResenaField3;
    private javax.swing.JRadioButton SiDieta3;
    private javax.swing.JButton conectar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
